### ISSUE TITLE
匯出成就到 Snap Hutao 發生問題

### ISSUE THREAD

**Issue by SSB-ARFCN** [HolographicHat/YaeAchievement#105]
使用 YaeAchievement 取得成就後 輸入1選擇匯入 "Snap Hutao" 後
![未命名](https://github.com/HolographicHat/YaeAchievement/assets/107019852/d6592ba2-1b62-472d-99e2-ef4a1dfbc4ca)
胡桃工具箱如同畫面中所看到的 整個成就頁面完全空白

**Comment by HolographicHat** [comment]
https://github.com/DGP-Studio/Snap.Hutao/issues/1763
