### ISSUE TITLE
进程异常退出，无法获取数据

### ISSUE THREAD

**Issue by Skinyi** [HolographicHat/YaeAchievement#106]
使用YaeAchievement导出成就会有如图报错提示，已尝试使用管理员权限运行。

![图片](https://github.com/HolographicHat/YaeAchievement/assets/23148648/fe5f4bda-87fe-469a-9e9c-0d421a71fdea)

**Comment by HolographicHat** [comment]
无法复现

**Comment by Skinyi** [comment]
我想起来了，可能是因为我删除了原有的原神自带启动器将游戏数据迁移到米哈游启动器的games文件夹下导致的
