### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by GuangDongPerson** [HolographicHat/YaeAchievement#111]
打开软件后 原神白屏然后直接闪退 稳定触发 (无论是否以管理员身份运行都一样)

**Comment by HolographicHat** [comment]
发一下日志文件 `%USERPROFILE%\AppData\LocalLow\miHoYo\原神\output_log.txt`

**Comment by GuangDongPerson** [comment]
[output_log.txt](https://github.com/user-attachments/files/16482263/output_log.txt)

**Comment by HolographicHat** [comment]
无法复现，能远程调试吗

**Comment by GuangDongPerson** [comment]
> 无法复现，能远程调试吗

可以  qq2902505215
