### ISSUE TITLE
Different achievement count on "Seelie.me" and "Paimon.moe" sites with json exported file

### ISSUE THREAD

**Issue by ComPfort** [HolographicHat/YaeAchievement#114]
Hello,

i found **miscount 1 achievement** number on sites "Seelie.me"  and "Paimon.moe" under category "Wonders of the World", **achievement name "Light Up the Dark Send forth some light."**

The site "**Paimon.moe" count correct** as it is in the game itself (number of achievements match),

![Paimon moe count achievement - Light up the Dark](https://github.com/user-attachments/assets/03871d94-a315-40bf-8381-4a3fc8882563)

where "**seelie.me" does not count** this achievement as done (with the json exported file from yaeachievement tool).
![seelie me-NOT-count](https://github.com/user-attachments/assets/504ad459-8aa2-424f-aeed-c3e6565884b0)

**Comment by HolographicHat** [comment]
try delete local storage data and re-import

**Comment by ComPfort** [comment]
Well, thank you for your answer, but i dont have that issue related with "browser site cache settings"  as i'm always using the "incognito mode" without saving any history etc...
I tried also manually clear ALL data from browser caches and import the file exported at the same time,
but it makes no difference regarding the count of achievements still differ by 1.
The site "seelie.me"  counts 1 achievemet **less** than "paimon.moe"  (that achievement is "Light Up the Dark Send forth some light")

my browser "settings":
![firefox-local history data clear-Clipboard-1](https://github.com/user-attachments/assets/1f499f2f-68d8-41b4-997c-2e74b80cfa56)

**Comment by HolographicHat** [comment]
try this
https://github.com/HolographicHat/YaeAchievement/actions/runs/10834273707/artifacts/1925658619
