### ISSUE TITLE
启动报错DirectoryNotFound

### ISSUE THREAD

**Issue by velentina1** [HolographicHat/YaeAchievement#119]
一开始报的HttpRequestException，关了火绒以后开始报DirectoryNotFound了，不知道什么情况，后续都是找不到路径
![Image_108327857147475](https://github.com/user-attachments/assets/3b970e31-458e-492a-a7b1-5cc66c4d8279)
![Image_108331036686380](https://github.com/user-attachments/assets/54899fc7-9fec-4afd-8e48-e2f3283c3d1d)

**Comment by HolographicHat** [comment]
看看哪个安全软件拦截了，如果没有手动删除 `C:\ProgramData\Yae` 目录后重试

**Comment by velentina1** [comment]
> 看看哪个安全软件拦截了，如果没有手动删除 `C:\ProgramData\Yae` 目录后重试

_(:зゝ∠)_看了一下programData下就莫得yae文件夹
![Image_110879171570252](https://github.com/user-attachments/assets/5772f21c-fb0b-4d03-8675-fbf6c6a429e2)
这咋整，火绒也关了，也没得别的安全软件了

**Comment by HolographicHat** [comment]
更新至最新版本后重试
