### ISSUE TITLE
大佬，这个问题怎么解决

### ISSUE THREAD

**Issue by cx-xingchuan** [HolographicHat/YaeAchievement#120]
打开之后提示这一串，修复DLL、.NET运行库、DirectX、VC++运行库都没有用，在之前的帖子的方法也尝试过了，全部没有用，该怎么解决
![20241121160912](https://github.com/user-attachments/assets/2f8d8bc8-bee6-471b-b828-1677f574b4df)

**Comment by HolographicHat** [comment]
更新至最新版本后重试

**Comment by cx-xingchuan** [comment]
> 更新至最新版本后重试

我用的就是最新版本，但是就是用不了，我打开原神是可以进游戏的，没有提示更新版本这些的

**Comment by cx-xingchuan** [comment]
> 更新至最新版本后重试



> > 更新至最新版本后重试
> 
> 我用的就是最新版本，但是就是用不了，我打开原神是可以进游戏的，没有提示更新版本这些的

已更新至5.2.2，已修复，感谢
