### ISSUE TITLE
請問存取權限不足怎麼解決

### ISSUE THREAD

**Issue by sqawer3310** [HolographicHat/YaeAchievement#121]
![未命名](https://github.com/user-attachments/assets/dd5c89f0-0b81-43c7-a322-7a73c984a9fd)

**Comment by HolographicHat** [comment]
使用浏览器能正常访问 [https://cn-cd-1259389942.file.myqcloud.com/schicksal/version](https://cn-cd-1259389942.file.myqcloud.com/schicksal/version) 吗

**Comment by sqawer3310** [comment]
不行 會變一個檔案

**Comment by HolographicHat** [comment]
下载文件是预期的行为
也许你可以重试一下(?

**Comment by sqawer3310** [comment]
不行欸 還是會跑出權限不足 有需要刪除什麼檔案讓他重新抓取嗎?

**Comment by HolographicHat** [comment]
try this (?
https://github.com/HolographicHat/YaeAchievement/actions/runs/12093354345/artifacts/2255974789

**Comment by sqawer3310** [comment]
可以使用了 非常感謝!
