### ISSUE TITLE
Paimon.moe 数据解析错误

### ISSUE THREAD

**Issue by iattach** [HolographicHat/YaeAchievement#14]
错误截图：
![image](https://user-images.githubusercontent.com/30409365/172040840-91888a0f-a501-4742-b15f-321a2afb0216.png)

用户：
海外用户，"oversea_api"已设置为true，原神账号为国际服账号

分析：
https://github.com/HolographicHat/YaeAchievement/blob/0de747e34421b554037c40cb053ee2b9a59877ef/export.js#L22
此行中"g"属性不存在，data解析错误。

**Comment by HolographicHat** [comment]
选择导出方式时，输入 `raw` 后将输出内容上传至 https://paste.mozilla.org/

**Comment by iattach** [comment]
https://paste.mozilla.org/UqSmeisv

**Comment by HolographicHat** [comment]
删除 `cache` 文件夹后重试
另外关于overseaapi选项，关闭时能够正常访问就无需启用

**Comment by iattach** [comment]
应该是overseaapi选项的问题，开启这个选项能稳定复现这个错误，关闭之后就没了。

之前因为网络错误开了这个选项，不知道为什么现在关了这个选项又可以了，就是在检查更新这步要等一段时间。

**Comment by HolographicHat** [comment]
忘记更新海外云函数的成就数据了(
另外关于检查更新，已经将CDN改为全球加速了，速度会有一定改善
