### ISSUE TITLE
网络错误，请检查网络后重试 (22-1)

### ISSUE THREAD

**Issue by Fnvelope** [HolographicHat/YaeAchievement#16]
昨天按alt+f4强制推出过软件，之后软件就“网络错误，请检查网络后重试 (22-1)”
游戏也上不去了

**Comment by HolographicHat** [comment]
![图片](https://user-images.githubusercontent.com/58809250/173825902-2e396a64-c2ab-41cb-b2be-2f7c448de158.png)
