### ISSUE TITLE
2.0怎么没有app.7z的下载路径呢

### ISSUE THREAD

**Issue by 450287475** [HolographicHat/YaeAchievement#21]
[2.0.0](https://github.com/HolographicHat/YaeAchievement/releases/tag/2.0.0) [Latest](https://github.com/HolographicHat/YaeAchievement/releases/latest)
适配原神2.8版本
修复了一些其它问题
无法打开: [.NET Runtime 6.0.7](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.7-windows-x64-installer)

Full Changelog: https://github.com/HolographicHat/YaeAchievement/compare/1.7.0...2.0.0

 Assets 3
[net6.0.7z](https://github.com/HolographicHat/YaeAchievement/releases/download/2.0.0/net6.0.7z)
472 KB
27 days ago
[Source code (zip)](https://github.com/HolographicHat/YaeAchievement/archive/refs/tags/2.0.0.zip)
28 days ago
[Source code (tar.gz)](https://github.com/HolographicHat/YaeAchievement/archive/refs/tags/2.0.0.tar.gz)
28 days ago

只有2个代码文件和net6.0的环境

**Comment by HolographicHat** [comment]
[net6.0.7z](https://github.com/HolographicHat/YaeAchievement/releases/download/2.0.0/net6.0.7z) 就是主程序包
