### ISSUE TITLE
Add English on executable file?

### ISSUE THREAD

**Issue by prpjzz** [HolographicHat/YaeAchievement#25]
Can you add a little bit of English to the executable file? I don't use Chinese as the main language for the system, so when I launch the application, all I see is that the squares come with question marks.

Well can I help you translate readme.md into English?

**Comment by HolographicHat** [comment]
> Can you add a little bit of English to the executable file?   

59a042019a881a09c6fffe5ba0d122481c2fde16

> Well can I help you translate readme.md into English?

Yes
![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square)

**Comment by prpjzz** [comment]
It's done. It took a long time because I had so little free time, but it was complete.
