### ISSUE TITLE
导入到SnapGenshin失败

### ISSUE THREAD

**Issue by itdengwenbin** [HolographicHat/YaeAchievement#29]

**Comment by HolographicHat** [comment]
需要更多信息

**Comment by itdengwenbin** [comment]
选择数字1后是把成就json放在剪切板里吧，再到snap原神上选择从剪切板导入提示“导入失败，导入的数据中包含不正确的项目。”

**Comment by itdengwenbin** [comment]
选择数字1后是把成就json放在剪切板里吧，再到snap原神上选择从剪切板导入提示“导入失败，导入的数据中包含不正确的项目。”

**Comment by HolographicHat** [comment]
将导出后剪贴板里的内容粘贴到下方网站
https://paste.mozilla.org

**Comment by chemharuka** [comment]
导出为json再导入snap.hutao会直接闪退，是json的问题还是snap.hutao的问题？
[export-20220828151220-paimon.txt](https://github.com/HolographicHat/YaeAchievement/files/9444631/export-20220828151220-paimon.txt)

**Comment by HolographicHat** [comment]
> 导出为json再导入snap.hutao会直接闪退，是json的问题还是snap.hutao的问题？ [export-20220828151220-paimon.txt](https://github.com/HolographicHat/YaeAchievement/files/9444631/export-20220828151220-paimon.txt)

选择 `Snap Genshin` 后在snap.hutao以剪贴板导入

**Comment by chemharuka** [comment]
> 

粘贴板内容：
[content.txt](https://github.com/HolographicHat/YaeAchievement/files/9450099/content.txt)

粘贴板导入胡桃时闪退

**Comment by chemharuka** [comment]
![image](https://user-images.githubusercontent.com/29047471/187363205-9a0693a1-aa3a-4921-b44b-3965dc9450c2.png)
另外导出到粘贴板时候报错，不过粘贴板有数据

**Comment by HolographicHat** [comment]
Fixed: 4b62901dbedeeca8bdcb21909ad74aafe54ae82f
