### ISSUE TITLE
请将程序完整解压后运行

### ISSUE THREAD

**Issue by tayleryu** [HolographicHat/YaeAchievement#30]
首次打开提示：请将程序完整解压后运行

**Comment by HolographicHat** [comment]
那么你能先 [解压](https://www.google.com.hk/search?client=firefox-b-d&q=7z+%E8%A7%A3%E5%8E%8B) 一下吗

**Comment by tayleryu** [comment]
那麻烦您告诉我 .exe文件如何解压

**Comment by HolographicHat** [comment]
不要把程序放在临时文件夹内运行

**Comment by tayleryu** [comment]
感谢作者提示 已经剪切到桌面，成功运行。
