### ISSUE TITLE
CMD doesn't support some characters

### ISSUE THREAD

**Issue by Julienraptor01** [HolographicHat/YaeAchievement#32]
I don't know if and how you can change it but it seems CMD doesn't support some characters.
The program can already be used whitout problem, it just look weird.
```log
----------------------------------------------------
YaeAchievement - ???????? (2.1)
https://github.com/HolographicHat/YaeAchievement
----------------------------------------------------
?????? (14180)
???:
[0] ?? (https://cocogoat.work/achievement, ??)
[1] SnapGenshin
[2] Paimon.moe
[3] Seelie.me
[4] ????
[5] ?????
??????(0-4): 2
???????? C:\Users\The Gamer\Downloads\YaeAchievement 2.1.0\export-20220902122833-paimon.json
??????
```
![image](https://user-images.githubusercontent.com/49841713/188121049-485d680f-362e-4d8d-9fb7-479c425087cb.png)

**Comment by HolographicHat** [comment]
Before next release, please use [snapshot version](https://github.com/HolographicHat/YaeAchievement/actions/) to solve this problem.

**Comment by Julienraptor01** [comment]
i tried the 2 compiled actions but same problem
https://github.com/HolographicHat/YaeAchievement/actions/runs/2978833950
https://github.com/HolographicHat/YaeAchievement/actions/runs/2979026068

**Comment by HolographicHat** [comment]
Open windows terminal(cmd/powershell) and execute `chcp`
paste result here

**Comment by Julienraptor01** [comment]
![image](https://user-images.githubusercontent.com/49841713/188309654-ba2da5b8-13f3-42f6-9883-d0c17b3cc49b.png)

**Comment by HolographicHat** [comment]
try [this](https://github.com/HolographicHat/YaeAchievement/suites/8125988969/artifacts/351921230)

**Comment by Julienraptor01** [comment]
Yep it now works
![image](https://user-images.githubusercontent.com/49841713/188310249-110ca594-7263-4116-ad3d-0700ee03142b.png)
Thanks ❤
