### ISSUE TITLE
导出为表格文件时出现异常

### ISSUE THREAD

**Issue by Polarforest** [HolographicHat/YaeAchievement#33]
在更新至最新版2.2.0后
导出的CSV表格文件内并没有原神3.1新增的成就
导出时提示Unable to find xxxxx in metadate
![-2744c7712ea08cdd.jpg](https://user-images.githubusercontent.com/84024443/192691358-c3439336-2971-4443-acdc-f4928e0ad0bc.jpg)
![-38b3a180b67790eb.jpg](https://user-images.githubusercontent.com/84024443/192691372-d1b12d8b-6a33-4ebe-a08d-94ab2f9f879f.jpg)

**Comment by HolographicHat** [comment]
成就元数据还没更新
如果急的话可以先导出到椰羊、胡桃等网站/软件

**Comment by Polarforest** [comment]
感谢回答，已经导出至椰羊正常使用
