### ISSUE TITLE
更新到2.2.1后无法使用

### ISSUE THREAD

**Issue by win98se** [HolographicHat/YaeAchievement#34]
![image](https://user-images.githubusercontent.com/11819816/193448935-fc9d3d43-d615-452b-88a8-a361d3ccd1c8.png)
提示`网络错误: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (cn-cd-1259389942.file.myqcloud.com:443)`

**Comment by HolographicHat** [comment]
请检查你的网络连接或更换网络后重试

**Comment by win98se** [comment]
平常上网没问题，原神也没问题，稍后再试看

**Comment by win98se** [comment]
后来重试后问题解决，感谢
