### ISSUE TITLE
2.2.1版本报毒

### ISSUE THREAD

**Issue by anpoz** [HolographicHat/YaeAchievement#36]
![image](https://user-images.githubusercontent.com/2825342/194269946-af7b2f5f-cb56-4fa8-a1e2-c66287f0680b.png)
![image](https://user-images.githubusercontent.com/2825342/194269651-173c3697-d426-4793-b0cd-e6d4238dda01.png)

**Comment by win98se** [comment]
@anpoz 请在[这里](https://www.microsoft.com/zh-cn/wdsi/filesubmission)以Home customer提交误判报告，让巨硬解除对这个文件的错误报毒
