### ISSUE TITLE
C:\ProgramData\Yae\YaeAchievement.dll  被360报毒。

### ISSUE THREAD

**Issue by pooneyy** [HolographicHat/YaeAchievement#40]
![image](https://user-images.githubusercontent.com/85266337/203806171-0bec6367-80c0-466e-bfb6-5f5aa7493cf8.png)

**Comment by HolographicHat** [comment]
属误报。
[VirusTotal](https://www.virustotal.com/gui/file/93dd8adb7949eddad0628a7af46970e2db3409d8d363cb20ff6500dd9c1bab69)
[微步云沙箱](https://s.threatbook.com/report/file/93dd8adb7949eddad0628a7af46970e2db3409d8d363cb20ff6500dd9c1bab69)
