### ISSUE TITLE
最新版2.4导出是空的

### ISSUE THREAD

**Issue by forchannot** [HolographicHat/YaeAchievement#42]
导出到椰羊显示无内容，导出为表格或者json是空文件

**Comment by forchannot** [comment]
![image](https://user-images.githubusercontent.com/100580891/206114264-70fa7ea3-f5c9-4007-8067-aa15559225bb.png)
![image](https://user-images.githubusercontent.com/100580891/206114319-985fb55d-976d-4f23-9255-16cb752390f0.png)

**Comment by CJYKK** [comment]
同，Paimon.moe的Json文件也是空的

**Comment by HolographicHat** [comment]
@CJYKK @forchannot 更新至2.4.1版本即可
