### ISSUE TITLE
安装NET Runtime后还是打不开

### ISSUE THREAD

**Issue by exquisitenightmare** [HolographicHat/YaeAchievement#45]

**Comment by HolographicHat** [comment]
`dotnet --list-runtimes`

**Comment by exquisitenightmare** [comment]
https://user-images.githubusercontent.com/119119338/210215284-139bafc3-5289-4762-8314-36112ce02ba7.png

**Comment by HolographicHat** [comment]
有报错吗

**Comment by exquisitenightmare** [comment]
> 有报错吗

没有，手动指定路径也试过了，点了还是没反应
