### ISSUE TITLE
2023.2.9原神更新后无法使用【未放置于同目录】(Error: 31-4302) Couldn't use to export the achievements after Genshin update

### ISSUE THREAD

**Issue by Mikachu2333** [HolographicHat/YaeAchievement#49]
如题，提示图片如下
![02月09日18时06分59秒](https://user-images.githubusercontent.com/63829496/217786042-a806811d-7bc9-43ad-a3b2-244d8579369e.png)

此问题出现于原神紧急更新“XXXNPC异常存在的问题”后出现。
关闭yaeach以后可以正常进行游戏。

**Comment by Mikachu2333** [comment]
根据错误代码，怀疑是原神在程序中增加了防止劫持dll的相关逻辑

**Comment by SaarChaffee** [comment]
客户端版本
![image](https://user-images.githubusercontent.com/53519746/217788370-895eb0a3-7310-464b-84b3-7a33bbc8f1e9.png)

**Comment by gurenn** [comment]
我的也一样，昨天在另一台电脑上还正常，今天2月9号就不行了

**Comment by Billy636** [comment]
一样哎，并没有放在同一目录，也是一样的毛病

**Comment by L-W-C00** [comment]
同样的问题+1

**Comment by zqsrios** [comment]
同样的问题
