### ISSUE TITLE
导出为JSON文件

### ISSUE THREAD

**Issue by BTMuli** [HolographicHat/YaeAchievement#55]
RT，建议添加一个导出为JSON文件的选项

**Comment by HolographicHat** [comment]
导出JSON格式的原始数据：在选择导出方式时，输入7并回车即可导出到文件
导出UIAF格式的数据：在选择导出方式时，输入1/5并回车即可导出到剪贴板

**Comment by BTMuli** [comment]
> 导出JSON格式的原始数据：在选择导出方式时，输入7并回车即可导出到文件
> 导出UIAF格式的数据：在选择导出方式时，输入1/5并回车即可导出到剪贴板

那导出 uiaf 格式的 json 呢

**Comment by HolographicHat** [comment]
**导出UIAF格式的数据：在选择导出方式时，输入1/5并回车即可导出到剪贴板**

**Comment by BTMuli** [comment]
> **导出UIAF格式的数据：在选择导出方式时，输入1/5并回车即可导出到剪贴板**

也就是不支持 uiaf 格式导出到文件咯

**Comment by HolographicHat** [comment]
支持导出UIAF JSON的CI Build：https://github.com/HolographicHat/YaeAchievement/suites/11970654079/artifacts/628076729
