### ISSUE TITLE
卡住了

### ISSUE THREAD

**Issue by silvikid** [HolographicHat/YaeAchievement#57]
点开之后就卡在这里,管理员模式启动也不行,
![image](https://user-images.githubusercontent.com/79353674/232274579-a0fd69eb-01ea-4537-a9e0-a9f785c3b098.png)
也安装了net7.03,原神如果正在运行就提示要关闭

**Comment by HolographicHat** [comment]
网络环境？

**Comment by silvikid** [comment]
哦,果然,换了手机热点立即好了,谢谢大佬
