### ISSUE TITLE
游戏进程异常退出

### ISSUE THREAD

**Issue by old-p** [HolographicHat/YaeAchievement#76]
<img width="735" alt="屏幕截图 2023-11-09 224754" src="https://github.com/HolographicHat/YaeAchievement/assets/56756384/96aa20b2-8334-443b-8b21-be6cd9389a38">
反复如此

**Comment by JIAN205** [comment]
出现了同样的问题，(国服)原神启动后在显示原神页面后直接闪退，不知道是否与系统更新有关，系统版本Windows 11 家庭中文版 23h2
